# Generated by Django 5.2.6 on 2025-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('AU', 'Australia')], max_length=20)),
                ('hobbies', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
